### PR TITLE
Do not register default MessageConverters

### LINKED ISSUE #21: Fix HttpMessageConverters registration
It seems like the configuration for `HttpMessageConverters` is ignored.

```java
(...)
public final class ClientConfigurationTest {
   (...)

    @Test
    public void shouldRegisterOnlyRegisteredConverters() {
        final List<HttpMessageConverter<?>> converters = ecbRestTemplate.getMessageConverters();
        assertThat(converters, hasSize(2));  // fails because never overwritten
    }
}
```

### PR DESCRIPTION
**Pull request by lukasniemeier-zalando**
Fixes #21

### CODE REVIEW

File: src/main/java/org/zalando/putittorest/RestClientPostProcessor.java [hunk 1]
```diff
@@ -112,8 +112,9 @@ private void configureTimeouts(final BeanDefinitionBuilder builder, final Timeou
 
     private String registerHttpMessageConverters(final String id) {
         return registry.register(id, HttpMessageConverters.class, () ->
-                BeanDefinitionBuilder.genericBeanDefinition(HttpMessageConverters.class).
-                        addConstructorArgValue(Registry.list(
+                BeanDefinitionBuilder.genericBeanDefinition(HttpMessageConverters.class)
+                        .addConstructorArgValue(false)
```
Comment (whiskeysierra) [inline src/main/java/org/zalando/putittorest/RestClientPostProcessor.java]: [Facepalm](https://www.youtube.com/watch?v=sPHx5qPbWAc)

**Comment by whiskeysierra** [comment]
:+1:
